### PR TITLE
fix: wrong Instructions in the readme.md to run the server-api locally

### LINKED ISSUE #362: Wrong Instructions in the readme.md to run the server-api locally
#### Describe the bug
The instructions in the readme.md to run the server-API locally mentions `npm start:prod` instead of `npm run start:prod`.

#### How to Reproduce
1) See the instructions for "Using Server API Locally" in its readme.md at https://github.com/asyncapi/server-api#using-it-locally

- Screenshots
Screenshot from 2023-10-24 23-45-19
- Link to GitHub repository with project that has issues: https://github.com/asyncapi/server-api
- Files that can help reproduce the issue: https://github.com/asyncapi/server-api#using-it-locally

#### Expected behavior
```
npm install 
npm run start:prod
```

### PR DESCRIPTION
**Pull request by maheshchandra10**
Fixes #362

### CODE REVIEW

**Review by princerajpoot20 — APPROVED** [review]
LGTM 🚀

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔 Thanks for the fix @maheshchandra10 !

**Comment by smoya** [comment]
I just noticed the commit prefix shouldn't have to be `fix:` but `doc:`. Now we are triggering a release 😓

**Comment by princerajpoot20** [comment]
🥲

**Pull request merged**
